config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "users#index"
  resources :users, only: [:show] do
    resources :comments, only: [:create]
    resources :messages,  only: [:new, :create]
  end
  resources :reminds,  only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

  def comment_day
    created_at.strftime("%H:%M")
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/remind.rb
class Remind < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :comments
  has_many :messages
  has_many :reminds

  validates :first_name, :last_name, :birthday, presence: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end
    user
  end

  def birth_day
    birthday.strftime("%m月%d日")
  end

  private

  def self.dummy_email(auth)
   "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :info, :warning, :danger
end

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:uid, :provider, :first_name, :last_name, :gender, :birthday])
  devise_parameter_sanitizer.permit(:account_update, keys: [:uid, :provider, :first_name, :last_name, :gender, :birthday])
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    Comment.create(comment_params)
    redirect_to user_path(params[:user_id])
  end

private

  def comment_params
    params.require(:comment).permit(:user_id, :birthday_user_id, :body, :image)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @user = current_user
    @message = Message.new
    @birthday_user = User.find(params[:user_id])
  end
  def create
    birthday_user_id = params[:user_id]
    @birthday_user = User.find(birthday_user_id)
    @message = Message.new(message_params)
    @message.save
    Slack.chat_postMessage text: "#{@birthday_user.last_name}さんに以下の誕生日メッセージを送信しました！\n-----------------------------------------\n#{@message.body}", username: "誕生日メッセージBot", channel: "#general"
    redirect_to :root
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :birthday_user_id, :body, :image)
  end
end

app/controllers/reminds_controller.rb
class RemindsController < ApplicationController

  def create
    @remind = Remind.new(remind_params)
    if @remind.save
      Slack.chat_postMessage text: "誕生日のリマインド設定をしました", username: "誕生日Bot", channel: "#general"
      redirect_to :root
    end
  end

  def notice_to_user
    today = Date.today
    @reminds = Remind.where(remind_date: today)
    if @reminds.present?
      @reminds.each do |remind|
        notify_to_slack(remind)
      end
    end
  end

  private

  def remind_params
    params.require(:remind).permit(:user_id, :birthday_user_id, :remind_date)
  end

  def notify_to_slack(remind)
  text = <<-EOC
-----------------------------
[#{Rails.env}] 新しいご意見が来ました。

▼誕生日の人
#{remind.birthday_user_id}
▼いつ
#{remind.remind_date}
  EOC

  Slack.chat_postMessage text: text, username: "Opinion Notifier", channel: "#general"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  private
  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @remind = Remind.new
  end

  def show
    @user = User.find(params[:id])
    @comments = Comment.where(birthday_user_id: @user.id)
    @comment = Comment.new(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_comments_result(user)
    if user.id == current_user.id
      content_tag :h4, '閲覧権限はありません♡'
    else
      render partial: 'user_comments'
    end
  end
end

app/views/comments/_comment.html.slim
.panel.panel-default
  .panel-heading
    ul.list-inline
      li= comment.comment_day
      li= comment.user.last_name
  .panel-body
    - if comment.body
      = comment.body
    - if comment.image
      = image_tag(comment.image)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Prepare
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    - flash.each do |key, value|
      - key = "info" if key == "notice"
      - key = "danger"  if key == "alert"
      = content_tag :div, value, class: "alert alert-#{key}"
    = yield

app/views/messages/new.html.slim
.container
  = link_to 'indexへ', root_path, class: 'btn btn-primary'

  .user_profile
    h1.center-block
      = "#{@birthday_user.last_name }#{@birthday_user.first_name}さんへのメッセージ"
    .message-form
    = form_for [@user, @message], html: { class: "form-inline"} do |f|
      = f.hidden_field :user_id, value: current_user.id
      .form
        .form-list
          = f.text_area :body, placeholder: 'put a message', class: 'form-control', row: 7
        .form-list
          = f.submit "Comment", class: "btn"

app/views/users/_user.html.slim
ul.user.well.well-sm.text-primary
  li.col-xs-5
    = link_to "#{user.last_name } #{user.first_name}", user_path(user.id)
  li.col-xs-2
    = user.birth_day

  li.col-xs-1
    = form_for @remind, html: { class: "form-inline"} do |f|
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :birthday_user_id, value: user.id
      = f.hidden_field :remind_date, value: user.birthday - 1.month
      = f.submit '1ヶ月', class: 'btn new_remind btn-info'

  li.col-xs-1
    = form_for @remind, html: { class: "form-inline"} do |f|
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :birthday_user_id, value: user.id
      = f.hidden_field :remind_date, value: user.birthday - 2.weeks
      = f.submit '2週間', class: 'btn new_remind btn-success'

  li.col-xs-1
    = form_for @remind, html: { class: "form-inline"} do |f|
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :birthday_user_id, value: user.id
      = f.hidden_field :remind_date, value: user.birthday - 1.week
      = f.submit '1週間', class: 'btn new_remind btn-warning'
        
  li.col-xs-1
    = form_for @remind, html: { class: "form-inline"} do |f|
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :birthday_user_id, value: user.id
      = f.hidden_field :remind_date, value: user.birthday - 3.days
      = f.submit '3日', class: 'btn new_remind btn-danger'
  - unless user == current_user
    li.col-xs-1
      = link_to '手紙', new_user_message_path(user.id), class: 'btn btn-primary'

app/views/users/_user_comments.html.slim
h4 コメント一覧
js-comments
  = render @comments
.col-md-8
  = form_for [@user, @comment], html: { class: "form-inline"} do |f|
    = f.hidden_field :user_id, value: current_user.id
    = f.hidden_field :birthday_user_id, value: @user.id
    .form
      .form-list
        = f.text_field :body, placeholder: 'put a comment', class: 'form-control'
      .form-list
        = f.file_field :image
      .form-list
        = f.submit "Comment", class: "btn"

app/views/users/index.html.slim
.container
  = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-primary'

  h1 ユーザー一覧
  = render @users

app/views/users/show.html.slim
.container
  = link_to 'indexへ', root_path, class: 'btn btn-primary'

  .user_profile
    h1.center-block
      = "#{@user.last_name }#{@user.first_name}さんのページ"
    
  .user-comments
    = user_comments_result(@user)